#!name=Add-on for Stephan🍄
#!desc=Этот модуль должен находиться выше

#Включает в себя полную настройку групп прокси и прочие индивидуальные правила.

#Последние изменения 20.04.2026 03:00

[Proxy Group]
SPOTIFYPROXY = url-test,🇫🇷ФРАНЦИЯ,🇧🇷БРАЗИЛИЯ,🇹🇷ТУРЦИЯ,🇺🇸США-2,🇮🇳ИНДИЯ,🇬🇧АНГЛИЯ-2,🇰🇿КАЗАХСТАН,🇮🇹ИТАЛИЯ,🇩🇪ГЕРМАНИЯ,🇪🇸ИСПАНИЯ,🇳🇱НИДЕРЛАНДЫ,🇬🇧АНГЛИЯ,🇭🇺ВЕНГРИЯ,🇱🇹ЛИТВА,🇨🇭ШВЕЙЦАРИЯ,🇺🇸США,🇨🇦КАНАДА|GEMINI,🇱🇻ЛАТВИЯ|TORRENT,🇵🇱ПОЛЬША,🇫🇮ФИНЛЯНДИЯ,use=true,interval=120,tolerance=150,timeout=2,url=https://open.spotify.com
INSTPROXY = load-balance,🇭🇺ВЕНГРИЯ,🇱🇻ЛАТВИЯ|TORRENT,🇲🇩МОЛДОВА,🇬🇧АНГЛИЯ-2,🇪🇸ИСПАНИЯ,🇺🇸США-2,🇮🇳ИНДИЯ,🇧🇷БРАЗИЛИЯ,🇱🇹ЛИТВА,🇵🇱ПОЛЬША,🇰🇿КАЗАХСТАН,🇹🇷ТУРЦИЯ,🇫🇮ФИНЛЯНДИЯ,🇯🇵ЯПОНИЯ,🇨🇦КАНАДА|GEMINI,🇬🇧АНГЛИЯ,🇩🇪ГЕРМАНИЯ,🇮🇹ИТАЛИЯ,🇨🇭ШВЕЙЦАРИЯ,🇺🇸США,use=true,interval=60,timeout=2,url=https://fbcdn.net
TGPROXY = load-balance,🇭🇺ВЕНГРИЯ,🇱🇻ЛАТВИЯ|TORRENT,🇲🇩МОЛДОВА,🇬🇧АНГЛИЯ-2,🇪🇸ИСПАНИЯ,🇺🇸США-2,🇮🇳ИНДИЯ,🇧🇷БРАЗИЛИЯ,🇱🇹ЛИТВА,🇵🇱ПОЛЬША,🇰🇿КАЗАХСТАН,🇫🇷ФРАНЦИЯ,🇫🇮ФИНЛЯНДИЯ,🇯🇵ЯПОНИЯ,🇨🇦КАНАДА|GEMINI,🇬🇧АНГЛИЯ,🇩🇪ГЕРМАНИЯ,🇮🇹ИТАЛИЯ,🇨🇭ШВЕЙЦАРИЯ,🇺🇸США,use=true,interval=60,timeout=2,url=https://www.telegram.org
DISCORDPROXY = fallback,🇨🇭ШВЕЙЦАРИЯ,🇫🇮ФИНЛЯНДИЯ,🇮🇹ИТАЛИЯ,🇩🇪ГЕРМАНИЯ,🇭🇺ВЕНГРИЯ,🇫🇷ФРАНЦИЯ,🇱🇻ЛАТВИЯ|TORRENT,🇵🇱ПОЛЬША,🇬🇧АНГЛИЯ-2,🇪🇸ИСПАНИЯ,🇱🇹ЛИТВА,🇲🇩МОЛДОВА,🇬🇧АНГЛИЯ,🇰🇿КАЗАХСТАН,use=true,interval=60,timeout=2,url=https://discord.com/api/v9/gateway
TIKTOKPROXY = url-test,🇰🇿КАЗАХСТАН,🇫🇮ФИНЛЯНДИЯ,🇩🇪ГЕРМАНИЯ,🇭🇺ВЕНГРИЯ,🇫🇷ФРАНЦИЯ,🇱🇻ЛАТВИЯ|TORRENT,🇵🇱ПОЛЬША,🇬🇧АНГЛИЯ-2,🇹🇷ТУРЦИЯ,🇱🇹ЛИТВА,🇨🇭ШВЕЙЦАРИЯ,🇲🇩МОЛДОВА,🇪🇸ИСПАНИЯ,🇬🇧АНГЛИЯ,🇮🇹ИТАЛИЯ,use=true,interval=60,tolerance=100,timeout=2,url=https://www.tiktok.com/favicon.ico
COPILOTPROXY = load-balance,🇭🇺ВЕНГРИЯ,🇱🇻ЛАТВИЯ|TORRENT,🇲🇩МОЛДОВА,🇬🇧АНГЛИЯ-2,🇪🇸ИСПАНИЯ,🇺🇸США-2,🇮🇳ИНДИЯ,🇧🇷БРАЗИЛИЯ,🇱🇹ЛИТВА,🇵🇱ПОЛЬША,🇰🇿КАЗАХСТАН,🇹🇷ТУРЦИЯ,🇫🇷ФРАНЦИЯ,🇫🇮ФИНЛЯНДИЯ,🇯🇵ЯПОНИЯ,🇨🇦КАНАДА|GEMINI,🇬🇧АНГЛИЯ,🇩🇪ГЕРМАНИЯ,🇮🇹ИТАЛИЯ,🇨🇭ШВЕЙЦАРИЯ,🇺🇸США,use=true,interval=60,timeout=2,url=https://login.microsoftonline.com/favicon.ico
GPTPROXY = url-test,🇭🇺ВЕНГРИЯ,🇺🇸США,🇲🇩МОЛДОВА,🇬🇧АНГЛИЯ-2,🇪🇸ИСПАНИЯ,🇺🇸США-2,🇮🇳ИНДИЯ,🇧🇷БРАЗИЛИЯ,🇱🇹ЛИТВА,🇵🇱ПОЛЬША,🇰🇿КАЗАХСТАН,🇹🇷ТУРЦИЯ,🇫🇷ФРАНЦИЯ,🇯🇵ЯПОНИЯ,🇫🇮ФИНЛЯНДИЯ,🇨🇦КАНАДА|GEMINI,🇬🇧АНГЛИЯ,🇩🇪ГЕРМАНИЯ,🇮🇹ИТАЛИЯ,🇨🇭ШВЕЙЦАРИЯ,🇱🇻ЛАТВИЯ|TORRENT,use=true,interval=60,tolerance=100,timeout=2,url=https://chat.openai.com/favicon.ico
GEMINIPROXY = load-balance,🇰🇿КАЗАХСТАН,🇫🇮ФИНЛЯНДИЯ,🇧🇷БРАЗИЛИЯ,🇭🇺ВЕНГРИЯ,🇺🇸США-2,🇫🇷ФРАНЦИЯ,🇯🇵ЯПОНИЯ,🇩🇪ГЕРМАНИЯ,🇱🇻ЛАТВИЯ|TORRENT,🇹🇷ТУРЦИЯ,🇨🇭ШВЕЙЦАРИЯ,🇪🇸ИСПАНИЯ,🇱🇹ЛИТВА,🇲🇩МОЛДОВА,🇮🇹ИТАЛИЯ,🇨🇦КАНАДА|GEMINI,🇺🇸США,use=true,interval=60,timeout=2,url=https://www.google.com/generate_204
SPEEDPROXY = url-test,🇫🇮ФИНЛЯНДИЯ,🇩🇪ГЕРМАНИЯ,🇫🇷ФРАНЦИЯ,🇭🇺ВЕНГРИЯ,🇱🇻ЛАТВИЯ|TORRENT,🇵🇱ПОЛЬША,🇬🇧АНГЛИЯ-2,🇹🇷ТУРЦИЯ,🇨🇭ШВЕЙЦАРИЯ,🇱🇹ЛИТВА,🇲🇩МОЛДОВА,🇪🇸ИСПАНИЯ,🇮🇹ИТАЛИЯ,🇬🇧АНГЛИЯ,🇰🇿КАЗАХСТАН,use=true,interval=60,tolerance=50,timeout=2,url=https://www.youtube.com/generate_204
BESTPROXY = load-balance,🇭🇺ВЕНГРИЯ,🇺🇸США,🇲🇩МОЛДОВА,🇬🇧АНГЛИЯ-2,🇪🇸ИСПАНИЯ,🇺🇸США-2,🇧🇷БРАЗИЛИЯ,🇱🇹ЛИТВА,🇵🇱ПОЛЬША,🇰🇿КАЗАХСТАН,🇫🇮ФИНЛЯНДИЯ,🇫🇷ФРАНЦИЯ,🇯🇵ЯПОНИЯ,🇹🇷ТУРЦИЯ,🇨🇦КАНАДА|GEMINI,🇬🇧АНГЛИЯ,🇩🇪ГЕРМАНИЯ,🇨🇭ШВЕЙЦАРИЯ,🇮🇹ИТАЛИЯ,🇱🇻ЛАТВИЯ|TORRENT,use=true,interval=60,timeout=2,url=http://cp.cloudflare.com/generate_204

[Rule]
DOMAIN-SUFFIX,kinopoisk.ru,DIRECT,pre-matching
IP-CIDR,5.28.195.2,DIRECT,no-resolve
RULE-SET,https://raw.githubusercontent.com/Krest-Neva/Shadowrocket/refs/heads/main/REJECT_RULES/REJECT_RULES_STD.list,REJECT-DICT
#RULE-SET,https://raw.githubusercontent.com/Krest-Neva/Shadowrocket/refs/heads/main/REJECT_RULES/REJECT_RULES_PLUS.list,REJECT-DICT
#RULE-SET,https://raw.githubusercontent.com/Krest-Neva/Shadowrocket/refs/heads/main/REJECT_RULES/REJECT_RULES_STD_SMALL.list,REJECT-DICT
#RULE-SET,https://raw.githubusercontent.com/Krest-Neva/Shadowrocket/refs/heads/main/REJECT_RULES/REJECT_RULES_PLUS_SMALL.list,REJECT-DICT
#RULE-SET,https://raw.githubusercontent.com/Krest-Neva/Shadowrocket/refs/heads/main/REJECT_RULES/SPLIT/REJECT_RULES_STD_1.list,REJECT-DICT
#RULE-SET,https://raw.githubusercontent.com/Krest-Neva/Shadowrocket/refs/heads/main/REJECT_RULES/SPLIT/REJECT_RULES_STD_2.list,REJECT-DICT
#RULE-SET,https://raw.githubusercontent.com/Krest-Neva/Shadowrocket/refs/heads/main/REJECT_RULES/SPLIT/REJECT_RULES_STD_3.list,REJECT-DICT
#RULE-SET,https://raw.githubusercontent.com/Krest-Neva/Shadowrocket/refs/heads/main/REJECT_RULES/SPLIT/REJECT_RULES_STD_4.list,REJECT-DICT
#RULE-SET,https://raw.githubusercontent.com/Krest-Neva/Shadowrocket/refs/heads/main/REJECT_RULES/SPLIT/REJECT_RULES_STD_5.list,REJECT-DICT
#RULE-SET,https://raw.githubusercontent.com/Krest-Neva/Shadowrocket/refs/heads/main/REJECT_RULES/SPLIT/REJECT_RULES_STD_6.list,REJECT-DICT
#RULE-SET,https://raw.githubusercontent.com/Krest-Neva/Shadowrocket/refs/heads/main/REJECT_RULES/SPLIT/REJECT_RULES_PLUS_1.list,REJECT-DICT
#RULE-SET,https://raw.githubusercontent.com/Krest-Neva/Shadowrocket/refs/heads/main/REJECT_RULES/SPLIT/REJECT_RULES_PLUS_2.list,REJECT-DICT
#RULE-SET,https://raw.githubusercontent.com/Krest-Neva/Shadowrocket/refs/heads/main/REJECT_RULES/SPLIT/REJECT_RULES_PLUS_3.list,REJECT-DICT
#RULE-SET,https://raw.githubusercontent.com/Krest-Neva/Shadowrocket/refs/heads/main/REJECT_RULES/SPLIT/REJECT_RULES_PLUS_4.list,REJECT-DICT
#RULE-SET,https://raw.githubusercontent.com/Krest-Neva/Shadowrocket/refs/heads/main/REJECT_RULES/SPLIT/REJECT_RULES_PLUS_5.list,REJECT-DICT
#RULE-SET,https://raw.githubusercontent.com/Krest-Neva/Shadowrocket/refs/heads/main/REJECT_RULES/SPLIT/REJECT_RULES_PLUS_6.list,REJECT-DICT
#RULE-SET,https://raw.githubusercontent.com/Krest-Neva/Shadowrocket/refs/heads/main/REJECT_RULES/SPLIT/REJECT_RULES_PLUS_7.list,REJECT-DICT
#RULE-SET,https://raw.githubusercontent.com/Krest-Neva/Shadowrocket/refs/heads/main/REJECT_RULES/SPLIT/REJECT_RULES_PLUS_8.list,REJECT-DICT
#RULE-SET,https://raw.githubusercontent.com/Krest-Neva/Shadowrocket/refs/heads/main/REJECT_RULES/SPLIT/REJECT_RULES_PLUS_9.list,REJECT-DICT
#RULE-SET,https://raw.githubusercontent.com/Krest-Neva/Shadowrocket/refs/heads/main/REJECT_RULES/SPLIT/REJECT_RULES_PLUS_10.list,REJECT-DICT
#RULE-SET,https://raw.githubusercontent.com/Krest-Neva/Shadowrocket/refs/heads/main/REJECT_RULES/SPLIT/REJECT_RULES_STD_SMALL_1.list,REJECT-DICT
#RULE-SET,https://raw.githubusercontent.com/Krest-Neva/Shadowrocket/refs/heads/main/REJECT_RULES/SPLIT/REJECT_RULES_STD_SMALL_2.list,REJECT-DICT
#RULE-SET,https://raw.githubusercontent.com/Krest-Neva/Shadowrocket/refs/heads/main/REJECT_RULES/SPLIT/REJECT_RULES_STD_SMALL_3.list,REJECT-DICT
#RULE-SET,https://raw.githubusercontent.com/Krest-Neva/Shadowrocket/refs/heads/main/REJECT_RULES/SPLIT/REJECT_RULES_PLUS_SMALL_1.list,REJECT-DICT
#RULE-SET,https://raw.githubusercontent.com/Krest-Neva/Shadowrocket/refs/heads/main/REJECT_RULES/SPLIT/REJECT_RULES_PLUS_SMALL_2.list,REJECT-DICT
#RULE-SET,https://raw.githubusercontent.com/Krest-Neva/Shadowrocket/refs/heads/main/REJECT_RULES/SPLIT/REJECT_RULES_PLUS_SMALL_3.list,REJECT-DICT