#!name=Yandex каки
#!desc=REJECT

[RULE]
#YANDEX каки✴️
DOMAIN-SUFFIX,afisha.yandex.ru,DIRECT
DOMAIN-SUFFIX,yastatic.net,DIRECT
DOMAIN,yandex.ru,REJECT-DICT,pre-matching
DOMAIN-SUFFIX,ad.mail.ru,REJECT,pre-matching
DOMAIN-SUFFIX,top-fwz1.mail.ru,REJECT,pre-matching
DOMAIN-SUFFIX,rs.mail.ru,REJECT,pre-matching
DOMAIN-SUFFIX,widgets.vk.com,REJECT-200,pre-matching
DOMAIN-SUFFIX,promotedby.vk.com,REJECT-200,pre-matching
DOMAIN-SUFFIX,adriver.ru,REJECT-200,pre-matching
DOMAIN-SUFFIX,criteo.com,REJECT-200,pre-matching
DOMAIN-SUFFIX,criteo.net,REJECT-200,pre-matching
DOMAIN-SUFFIX,moatads.com,REJECT-200,pre-matching
DOMAIN-SUFFIX,scorecardresearch.com,REJECT-200,pre-marching
DOMAIN-SUFFIX,serving-sys.com,REJECT-200,pre-matching
DOMAIN-SUFFIX,cdn.jsdelivr.net,REJECT-200,pre-matching
DOMAIN-SUFFIX,content-sdk.cdn.yandex.net,REJECT,pre-matching
DOMAIN-SUFFIX,directcdn.net,REJECT,pre-matching
DOMAIN-SUFFIX,frontend.vh.yandex.ru,REJECT,pre-matching
DOMAIN-SUFFIX,kp.yandex.ru,REJECT,pre-matching
DOMAIN-SUFFIX,moikrug.ru,REJECT,pre-matching
DOMAIN-SUFFIX,offer.cdn.yandex.net,REJECT,pre-matching
DOMAIN-SUFFIX,ok.video.yandex.ru,REJECT,pre-matching
DOMAIN-SUFFIX,promocodes.cdn.yandex.net,REJECT,pre-matching
DOMAIN-SUFFIX,shri.yandex.net,REJECT,pre-matching
DOMAIN-SUFFIX,spb.video.yandex.ru,REJECT,pre-matching
DOMAIN-SUFFIX,tm.yandex.ru,REJECT,pre-matching
DOMAIN-SUFFIX,video.yandex.ru,REJECT,pre-matching
DOMAIN-SUFFIX,web-antiadblock.nice.x.yandex-team.ru,REJECT,pre-matching
DOMAIN-SUFFIX,web-usocial.yandex.ru,REJECT,pre-matching
DOMAIN-SUFFIX,yandexadexchange.net,REJECT,pre-matching
DOMAIN-SUFFIX,yandex-rtb.cdn.yandex.net,REJECT,pre-matching
DOMAIN-SUFFIX,yandex-rtb-preview.cdn.yandex.net,REJECT,pre-matching
DOMAIN-SUFFIX,yanet.ru,REJECT,pre-matching
DOMAIN-SUFFIX,yanetcom.ru,REJECT,pre-matching
DOMAIN-SUFFIX,my.com,REJECT,pre-matching
DOMAIN-SUFFIX,cnt.my.com,REJECT,pre-matching
DOMAIN-SUFFIX,adj.st,REJECT,pre-matching
URL-REGEX,^https?://(.*)\.yandex\.(ru|com)/ad/.*$,REJECT-DICT,pre-matching
URL-REGEX,^https?://(.*)\.yandex\.(ru|com)/yabs/.*$,REJECT-DICT,pre-matching
URL-REGEX,^https?://(.*)\.yandex\.(ru|com)/bs/.*$,REJECT-DICT,pre-matching
URL-REGEX,^https?://(.*)\.yandex\.(ru|com)/direct/.*$,REJECT-DICT,pre-matching
URL-REGEX,^https?://(.*)\.yandex\.(ru|com)/rtb/.*$,REJECT-DICT,pre-matching
URL-REGEX,^https?://(.*)\.yandex\.(ru|com)/web-usocial/.*$,REJECT-DICT,pre-matching
URL-REGEX,^https?://(.*)\.yandex\.(ru|com)/yandex-ads/.*$,REJECT-DICT,pre-matching
URL-REGEX,^https?://(.*)\.yandex\.(ru|com)/zen/.*\?ad.*$,REJECT-DICT,pre-matching
URL-REGEX,^https?://yandex\.(ru|com)/clck/click.*$,REJECT,pre-matching
URL-REGEX,^https?://yandex\.(ru|com)/ads/v4/ad.*$,REJECT-DICT,pre-matching
URL-REGEX,^https?://yandex\.(ru|com)/an/count/.*$,REJECT,pre-matching
URL-REGEX,^https?://yandex\.(ru|com)/an/rtbcount/.*$,REJECT,pre-matching
URL-REGEX,^https?://baobab\.market\.yandex\.(ru|com)/safeclick/json.*$,REJECT-DICT,pre-matching
URL-REGEX,^https?://media-adv\..*\.yandex\.(ru|com)/.*$,REJECT,pre-matching
URL-REGEX,^https?://adfstat\.yandex\.(ru|com)/.*$,REJECT-TINYGIF,pre-matching
URL-REGEX,^https?://market\.yandex\.(ru|com)/ecom-assistant\?.*$,REJECT-DICT,pre-matching
URL-REGEX,^https?://ipa\.market\.yandex\.(ru|com)/api/v1\?.*dictionary=1.*$,REJECT-DICT,pre-matching
URL-REGEX,^https?://ipa\.market\.yandex\.(ru|com)/api/v1\?.*name=getToggles.*$,REJECT-DICT,pre-matching
URL-REGEX,^https?://ipa\.market\.yandex\.(ru|com)/api/v1\?.*name=resolveGlobalDeliveryPoint.*$,REJECT-DICT,pre-matching
URL-REGEX,^https?://api\.plus\.yandex\.net:443/.*$,REJECT-DICT,pre-matching
URL-REGEX,^https?://infocenter\.rasp\.yandex-net\.ru:443/.*$,REJECT,pre-matching
URL-REGEX,^https?://suburban-trains\.s3\.yandex\.net:443/.*$,REJECT,pre-matching
URL-REGEX,^https?://export\.rasp\.yandex-net\.ru:443/.*$,REJECT,pre-matching
URL-REGEX,^https?://stable\.carsharing\.yandex\.net:443/.*$,REJECT,pre-matching
URL-REGEX,^https?://tc\.mobile\.yandex\.net:443/.*$,REJECT,pre-matching
URL-REGEX,https://yandex\.com/clck/click.*,REJECT

[URL Rewrite]
^http(s?)://(.*?)\?(.*)&?utm_(.*) http$1://$2?$3 302
^http(s?)://(.*?)\?(utm_.*)&?(.*) http$1://$2?$3 302
^http(s?)://(.*?)\?utm_(.*) http$1://$2 302
^http(s?)://(.*?)\?(.*)&?yclid=(.*) http$1://$2?$3 302
^http(s?)://(.*?)\?yclid=(.*) http$1://$2 302
^http://(www\.)?yandex\.ru https://yandex.com 302
^https://(www\.)?yandex\.ru https://yandex.com 302

[MITM]
hostname = %APPEND% yandex.ru, yandex.com, ya.ru, *.yandex.ru, *.yandex.com, *.ya.ru